### ISSUE TITLE
FB: Bubble just opens Flycast-Vita

### ISSUE THREAD

**Issue by sffan82** [DRok17/Multi-Builder#17]
Builder makes bubble, opens emulator, but won't run the CDI.

**Comment by DRok17** [comment]
Is the rom in the correct folder as shown in args.txt? What game is this?

**Comment by sffan82** [comment]
I retried the process and it works now, except it takes several times of opening the bubble before the game starts. Each time I press on the bubble the splash screen comes up but then closes. Eventually the game runs after 5-10 presses. This happens for all the bubbles I made with Multibuilder (retroarch, N64, flycast, etc....)

**Comment by DRok17** [comment]
Ah ic, good. Glad it's working,

In regards to the opening bubbles issue, it's a known issue but not something I can fix or reproduce consistently. I've assumed it's due to the Vita not being able to open Flycast/RetroArch or whatever application required in time and therefore does not open as it should.
